name: TRILL_RTD
channels:
  - conda-forge
  - defaults
  - pytorch
  - pyg
dependencies:
  - python=3.8
  - pip
  - openmm
  - swig
  - pdbfixer
  - pytorch=1.13.1=py3.8_cpu_0
  - cpuonly
  - pyg=2.3.1=py38_torch_1.13.0_cpu 
  - pytorch-cluster=1.6.1=py38_torch_1.13.0_cpu 
  - pytorch-sparse=0.6.17=py38_torch_1.13.0_cpu 
  - pytorch-scatter=2.1.1=py38_torch_1.13.0_cpu
  - mkl=2024.0
  - pip:
    - lightning-fabric==2.2.5
    - h5py
    - setuptools
    - pytorch-lightning
    - transformers
    - datasets
    - biotite
    - bokeh
    - umap-learn
    - pyfiglet
    - fair-esm
    - GitPython
    - xgboost
    - pandas
    - rdkit
    - e3nn
    - biopython==1.81
    - spyrmsd
    - SentencePiece
    - omegaconf
    - hydra-core
    - icecream
    - chardet
    - cchardet
    - skops
    - fairscale
    - deepspeed
    - sphinx-argparse
    - myst-parser
    - sphinx-rtd-dark-mode
    - sphinx-copybutton
    - biobb_vs
    - scikit-optimize
